# Generated by Django 2.2.17 on 2021-03-15 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_business', models.BooleanField()),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('picture', models.ImageField(upload_to='')),
                ('time', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eventmakerapp.Account')),
                ('website', models.URLField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmakerapp.Event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='eventmakerapp.Account')),
                ('comments', models.ManyToManyField(related_name='comments', through='eventmakerapp.Comment', to='eventmakerapp.Event')),
                ('joins', models.ManyToManyField(related_name='joins', to='eventmakerapp.Event')),
                ('likes', models.ManyToManyField(related_name='likes', to='eventmakerapp.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmakerapp.Business'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmakerapp.User'),
        ),
    ]
