# Generated by Django 2.2.17 on 2021-03-20 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='comments',
        ),
    ]
