# Generated by Django 2.2.17 on 2021-04-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='locationName',
            field=models.TextField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_business',
            field=models.BooleanField(default=False, verbose_name='Do you represent a business?'),
        ),
    ]
