# Generated by Django 2.2.17 on 2021-03-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0002_remove_event_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commented', through='eventmakerapp.Comment', to='eventmakerapp.User'),
        ),
    ]
