# Generated by Django 2.2.17 on 2021-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0002_auto_20210322_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, verbose_name='About you'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_business',
            field=models.BooleanField(default=False, verbose_name='Are you a business?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Profile picture'),
        ),
    ]
