# Generated by Django 2.2.17 on 2021-04-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0002_auto_20210403_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='joins',
        ),
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
    ]
