# Generated by Django 2.2.17 on 2021-03-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0003_auto_20210321_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
