# Generated by Django 2.2.17 on 2021-03-20 19:02

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0003_event_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default='55.8719,-4.2883', max_length=63)),
            ],
        ),
    ]
