# Generated by Django 2.2.17 on 2021-03-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0003_auto_20210323_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
