# Generated by Django 2.2.17 on 2021-03-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0004_remove_userprofile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='defaultProfilePic.png', upload_to='', verbose_name='Profile picture'),
        ),
    ]
