# Generated by Django 2.2.17 on 2021-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0005_auto_20210328_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(default='NoEventImage.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='defaultProfilePic.jpg', upload_to='', verbose_name='Profile picture'),
        ),
    ]
