# Generated by Django 2.2.17 on 2021-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0006_auto_20210321_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='../static/images/chilling.png', upload_to=''),
        ),
    ]
