# Generated by Django 2.2.17 on 2021-03-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0006_auto_20210321_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
