# Generated by Django 2.2.17 on 2021-03-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmakerapp', '0007_auto_20210322_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='chilling.png', upload_to=''),
        ),
    ]
